services:
  firebase:
    container_name: ${APP_NAME}-firebase
    build:
      context: .
      dockerfile: firebase/Dockerfile
    ports:
      - ${FIREBASE_PORT}:9099
    volumes:
      - ./firebase:/firebase
    restart: always
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - ${APP_PORT}:8080
    environment:
      FIREBASE_SECRET: '{"type": "service_account","project_id": "emulator"}'
      FIREBASE_API_IDENTITY_TOOL_KIT: http://firebase:9099/identitytoolkit.googleapis.com
      FIREBASE_API_SECURE_TOKEN: http://firebase:9099/securetoken.googleapis.com
      FIREBASE_API_KEY: emulator
      FIREBASE_AUTH_EMULATOR_HOST: firebase:9099
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - firebase
